FROM python:3.12-slim

WORKDIR /app

# Копируем все файлы (включая main.py)
COPY . .

# Добавляем mysql-connector-python в список устанавливаемых пакетов
RUN pip install --no-cache-dir \
    uvicorn \
    fastapi \
    mysql-connector-python

EXPOSE 5000

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]